### PR TITLE
Refactor security group rules

### PR DESCRIPTION
**Pull request by marcransome**
This change replaces all inline `ingress` and `egress` security group rules with `aws_vpc_security_group_ingress_rule` and `aws_vpc_security_group_egress_rule` resources.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by sienkin — APPROVED** [review]

**Pull request merged**
